### ISSUE TITLE
Only adds 1 txt at a time not follow up txt files

### ISSUE THREAD

**Issue by stirlo** [stirlo/txt_to_ICS_Prayer_Times#2]
Either adjust use guides or work out how to process multiple at once

**Comment by miguellords** [comment]
I think this will help you.
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive
